s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print("python programming".title())
print(s.center(40,"*"))
print(s.count("T"))
print(s.endswith("es"))
print(s.endswith("esh"))
print(s.find("log"))
print(s.index("T"))
print(s.index("T",2))
print("123".isnumeric())
print("tops".isnumeric())
print("tops".isalpha())
print("123".isalpha())
print("tops123".isalnum())
print("123".isalnum())
print("tops".isalnum())
print(s.istitle())
print(" ".isspace())
print("Hello".replace("l","w"))
